# Generated by Django 5.2.14 on 2026-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default=1, max_length=200, verbose_name='Уникальный идентификатор локации'),
        ),
    ]
