# Generated by Django 5.2.14 on 2026-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=200, verbose_name='Уникальный идентификатор локации'),
        ),
    ]
