# Generated by Django 5.2.14 on 2026-05-14 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, verbose_name='Уникальный идентификатор локации'),
        ),
    ]
