# Generated by Django 5.2.14 on 2026-05-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
